### ISSUE TITLE
Software update needed

### ISSUE THREAD

**Issue by laurelegros88** [getstation/desktop-app#107]
I tried to install the Mac version of the app on my macbook but got the following message: 

“Station.dmg” can’t be opened because Apple cannot check it for malicious software. This software needs to be updated. Contact the developer for more information.

**Comment by benzntech** [comment]
You can’t open the application “Station” because this application is not supported on this Mac.
![image](https://github.com/getstation/desktop-app/assets/4044180/7e5272a1-5a67-442a-82a9-d457847dd606)

![image](https://github.com/getstation/desktop-app/assets/4044180/74fa0c5c-7276-4f04-9fbb-c32a73594171)

**Comment by viktor44** [comment]
Hi, I have exactly the same OS version and it works fine.
Maybe you've downloaded wrong DMG? There are two different distributions for x86 and Apple M processors.

**Comment by viktor44** [comment]
@benzntech still have the issue?
