### ISSUE TITLE
Gmail not working and whatsapp not showing the QR code

### ISSUE THREAD

**Issue by a-Mafalda** [getstation/desktop-app#117]
Hi! 
When I try to add my Gmail account it shows the following error: Erro 400: invalid_request
Missing required parameter: client_id

Whatsapp is ln an infinite QR code lead and it doesn't appear even after quitting and opening the app again. 

Can someone give me any tips? 
Telegram worked fine!

**Comment by haztolt** [comment]
I'm having the same issue also. Using Mac Monterey version 12.3.1 (21E258)

**Comment by a-Mafalda** [comment]
Yes, I also tried all that multiple times and nothing. 

Station developers, can we take a look at this, please? Or does any of you has a tip about a similar app? 

Thank you!

**Comment by basiljabir** [comment]
I have the same problem. Is this discontinued or something?

![image](https://user-images.githubusercontent.com/16590303/165303794-f1d4b19b-66be-4a3e-bb14-982742a48060.png)
![image](https://user-images.githubusercontent.com/16590303/165303664-c3e937f2-6d8f-475d-9f85-e3375cb518b4.png)

**Comment by BlueKittyMeow** [comment]
I've been having the same issue with Gmail since March 4th (Windows 10 and Windows 11). Disappointing to see that there seems to be no movement towards resolving this. Just checked again 4/26/22 on Windows 10 and the same issue persists.

**Comment by robwired** [comment]
Does this mean that Station no longer supports Google apps? Is Station shutting down development?

**Comment by robwired** [comment]
It's been a month and while I don't like that Google is much of the web, without Google support Station is basically unusable for anyone using Google sign-on now.

Since the team hasn't responded for a month can we assume it's something that isn't going to change?

Which app do the rest of you recommend upgrading to as a replacement?

**Comment by kaiying1991** [comment]
Hi @robwired, I am currently using Rambox as an alternative.

**Comment by a-Mafalda** [comment]
> Hi @robwired, I am currently using Rambox as an alternative.

Thank you for the tip. I think we won't get anywhere with Station, such a pity.

**Comment by haztolt** [comment]
> Hi @robwired, I am currently using Rambox as an alternative.

Nice one!!

**Comment by evayor** [comment]
Thank you for the very detailed reply and multiple suggestions. 

> For my needs, I actually just settled on using the Vivaldi browser. I needed a tiled view of live webpages as a heads up display for my work study students and that ended up free and works great.

Do you use the speed dial function of Vivaldi as a replacement for Station? Because I don't really understand how it can work as an all-in-one messenger, which is what I needed to stop having so many open apps on my desktop.

**Comment by TheRealGramdalf** [comment]
This project is currently not being actively maintained (i.e. the owners aren't going through the issues) but if the community steps in, we may be able to help.

Here is my proposal:
@F4Ke and @magne4000, would you be able to answer my questions? It would be really helpful.

1. How likely is it that someone (I could try and do it if I learned the skills) could port this to Tauri? It looks like the main language used is Typescript, which is similar to Javascript, but I don't know if it would require any changes in order to port it. Based off of what you know, how hard would it be?
2. From what I can tell, I think the problem with Google signin is that the app requires an API key of some sort (the Client ID mentioed). From a quick google search, the solution may just be obtaining a new key and slotting it in in the correct place. My theory is that the maintainers just didn't have time to update the API key, and so it just expired. That is why no one can sign in. @F4Ke and @magne4000, can you confirm this?
3. I would be willing to spend my time developing and maintaining this wonderful app, but I would preferably have some help from the original devs. Are you open to this option @F4Ke and @magne4000 (sorry for the repeated mentions, I just want to make sure you see this).

So what do you think? Are there any people in the community that have the knowledge to answer these questions, and/or help if a new project is made in Tauri/I become the maintainer?

**Comment by magne4000** [comment]
@TheRealGramdalf 
> 1. How likely is it that someone (I could try and do it if I learned the skills) could port this to Tauri? It looks like the main language used is Typescript, which is similar to Javascript, but I don't know if it would require any changes in order to port it. Based off of what you know, how hard would it be?

Last time I checked (more than a year ago), Tauri was lacking functionalities around Webviews support and security. I do not remember exactly what were the issues though. Here are a few things to note:
- We started implementing Chrome Extensions supports in Station. I assume this will not work in Tauri
- We [preload](https://www.electronjs.org/fr/docs/latest/tutorial/context-isolation) scripts in all Webviews
- We communicate with Webviews (send and receive messages, with handlers created by preload script)
- And more that I forget

In Station, there is a good chunk of code living in a "Worker" process, [with it's own framework](https://github.com/getstation/desktop-app/tree/main/app/services), that is just a renderer without a Window. This has been done to circumvent an issue with [main process blocking the renderers](https://github.com/electron/electron/issues/12098).
This Worker handles all the internals of Station, and allows processes to communicate with each others. Currently it's kinda slow because of how Electron works, it would benefit being re-implemented in a child process of the main process (so for Tauri in Rust).

Regarding the Typescript part, Tauri surely has tutorials that explains how to properly dev and build it to JS.

> 2. From what I can tell, I think the problem with Google signin is that the app requires an API key of some sort (the Client ID mentioed). From a quick google search, the solution may just be obtaining a new key and slotting it in in the correct place. My theory is that the maintainers just didn't have time to update the API key, and so it just expired. That is why no one can sign in. @F4Ke and @magne4000, can you confirm this?

Actually, we closed the project on Google's side, so the key is indeed expired. There are 2 solutions:
- Create another API key with a new Google account
- Update [gmail definition](https://github.com/getstation/desktop-app/blob/9ed5d928aaed8e17153315273e9249f83e4a1c17/manifests/definitions/14.json) to remove `bx_multi_instance_config` and update `start_url` so there is no reference to `userIdentity` in it. It will bypass the first installation screen where you have to choose an account (that's the part that need the Google API key). The only drawback is that, if you have multiple Gmail installed, Station will have more difficulties finding the right Gmail App to go to when you click a Gmail link from another App (but that's currently bugged so not that big of a deal IMO)

> 3. I would be willing to spend my time developing and maintaining this wonderful app, but I would preferably have some help from the original devs. Are you open to this option @F4Ke and @magne4000 (sorry for the repeated mentions, I just want to make sure you see this).
> 
> So what do you think? Are there any people in the community that have the knowledge to answer these questions, and/or help if a new project is made in Tauri/I become the maintainer?

You can ping me whenever you have a bunch of questions.

If you eventually become familiar with the code base I could put you as a maintainer if this repo.

Rewriting this for Tauri will require almost a full rewrite of the app though. The only thing I would keep are the [manifests definitions](https://github.com/getstation/desktop-app/tree/9ed5d928aaed8e17153315273e9249f83e4a1c17/manifests), and some business logic found in the Worker. I say that because a good chunk of the code base is heavily Electron related.

If you choose to keep it under Electron, just know that upgrading Electron is horrendous, some versions took us weeks to integrate.

If I haven't discouraged you :sweat_smile:, good luck with this endeavour :mechanical_arm:!

**Comment by TheRealGramdalf** [comment]
Thanks for the information @magne4000!
Unfourtunately, life caught up with me. I'm pretty busy at the moment, but I'll leave this on the backburner. There may not be a need, given that by now ferdium has been released, but if it arises in the future, I may look into this again. The information you have there is really valuable.

Sorry for not replying sooner, it's a combination of life and notifications not being set up.
