### ISSUE TITLE
400 Authorization Error when connecting to GMail

### ISSUE THREAD

**Issue by gupsybabe** [getstation/desktop-app#124]
Gmail App. Clicking on Add a new account opens a browser. 
I enter sign in details. I get google verification. 
Then it shows 400 Authorization Error.
I tried switching from Chrome to Firefox, same 400 Auth Error.

**Comment by yasgreen93** [comment]
I also get this issue:
> Authorization Error
Error 400: invalid_request
Missing required parameter: client_id
<img src="https://user-images.githubusercontent.com/15678246/175344788-b63130cc-8ab5-43ce-acc2-df1c7f6a2e74.png" alt="image of the error" width="400">

Steps to replicate:
1. Click sign in button on any google app (I chose calendar)
2. Opens browser (Brave for myself) to log into your google account.
3. Get 400 error.

**Comment by kayd360** [comment]
I know why this error is happening. When you signin - it launches your default browser with google authentication. The problem is your default browser is already logged in with a google account and has cookies etc saved. It works fine if you clear all cache or singout all accounts and then from station start logging in 1 by 1. The perfect solution would be to have a wrapper inside station for google account authentication (It's pretty basic one that you would use for any webapps)

**Comment by kayd360** [comment]
please help with this. Unable to use it

**Comment by system-dump** [comment]
Also getting the same issue.
![2022-06-30 12_17_26-Sign in - Google Accounts](https://user-images.githubusercontent.com/76009091/176740688-1c9c03ee-20db-4b2c-ad84-e60c8aae9362.png)
![2022-06-30 12_23_09-Sign in - Google Accounts](https://user-images.githubusercontent.com/76009091/176740728-f6ac2ceb-efd4-4c59-9ae5-80040409b459.png)

**Comment by rewritablehere** [comment]
same here. need help with this

**Comment by dphaener** [comment]
Upvoting to follow this

**Comment by soundsgay** [comment]
Experiencing this issue as well
