### ISSUE TITLE
Rename Instances

### ISSUE THREAD

**Issue by gravityfargo** [getstation/desktop-app#126]
Self explanatory feature request ;D

**Comment by viktor44** [comment]
No it doesn't.
What is it about?

**Comment by viktor44** [comment]
Close due to inactivity

**Comment by Chirrut-Spine-ngo** [comment]
Can we reopen it? For a couple of services, I have multiple instances. It would be **very** helpful if I could rename them, give them nicknames and/or even change the usericons to differentiate between them. For instance, now I have 3 WhatsApp-icons below eachother and I have to actually click on each to see which is which.

**Comment by c4tb3rt** [comment]
Can we reopen this issue? I have multiple instances of more than one service. I would **love** to have the possibility to rename the instance (for example: instead of 'WhatsApp' 'WA Personal') or to give them a nickname behind the service name (for example 'Whatsapp (Personal)') and/or to change the icon per instance of a service.
I know Ferdium offers this possibility and it is very useful.
