### ISSUE TITLE
I'm not sure how to "contact" the project owner, so here's that

### ISSUE THREAD

**Issue by uniquekaiser** [getstation/desktop-app#157]
Hi! @hugomano @magne4000 @F4Ke @jvincent42 @MatthD 

I have a couple of questions regarding station, namely:
- Is there a workaround to being able to install Chrome Extensions? I want to be able to use some GPT chrome extensions on top of the webapps.
- How can we suggest apps to be available in the directory?
-  Is there a way to define multiple languages so spell check can be done for several languages?

Thanks!

David

**Comment by magne4000** [comment]
Hi @uniquekaiser :wave:

:warning: As stated on the README, this project is not actively maintained (at least by the founding members, me included). That being said, I still review submited Pull Requests.

> Is there a workaround to being able to install Chrome Extensions? I want to be able to use some GPT chrome extensions on top of the webapps.

Sadly no. The Chrome Extension compatibility layer was one of the hardest functionnality to maintain on Station, so unless a member of the community has the courage to carry on, it will remain unsupported.

> How can we suggest apps to be available in the directory?

Any definition can be added through a new JSON file created in https://github.com/getstation/desktop-app/tree/main/manifests/definitions folder. A simple example: https://github.com/getstation/desktop-app/blob/main/manifests/definitions/102.json
And you need to submit a Pull Request so that I can review and merge it.

> Is there a way to define multiple languages so spell check can be done for several languages?

Probably? But it would need to be looked up by someone in the community for feasability and implementation.
