### ISSUE TITLE
Wishlist: Open pages in tabs

### ISSUE THREAD

**Issue by dblapps** [getstation/desktop-app#182]
Would be really nice if pages selected from an app in the sidebar could be opened in tabs across the top of the station window, rather than in separate windows.  Would also be nice if the tabs across the top remained associated with the selected sidebar app, so each sidebar app has its own set of tabs.

FWIW, I've been using shift, but those guys are *really* bad about just shoving changes to the way their software works down customers throats, and ignoring and brushing off complaints from users.  So I've been looking at switching to Station.  The tabs thing is something shift supported reasonably well in the past, but their latest version totally breaks it.  If Station supported this, I'd switch in a heartbeat.

**Comment by viktor44** [comment]
Maybe I'm wrong but IMHO it completely breaks the idea of this application.
@magne4000 what do you think?

**Comment by magne4000** [comment]
I remember that we (the original Station team) discussed this at several occasions in the past, but the conclusion always was that it would complexify the UI and the different flows too much (I do not remember the exact pros and cons though).
I know that the current solution is not perfect, but we are not going forward with most feature requests.
The original team is not working on it anymore, and accepting feature requests would require deep knowledge of the current codebase and users flows so that we can stay true to what Station is.

**Comment by magne4000** [comment]
I haven't tried it in a long time, but perhaps Wavebox could be a more fitting solution for your workflow @dblapps?
