### ISSUE TITLE
Microsoft Teams doesn't stay logged in and can't log back in.

### ISSUE THREAD

**Issue by phiberr** [getstation/desktop-app#20]
Microsoft Teams works for a time, but then shows a message from Teams.
"We're sorry -- We've run into an issue.
Try Again
If that doesn't work, try signing out and back in."

Clicking Try Again doesn't appear to do anything and doesn't work.
Clicking the sign out link opens a browser window in which I'm not signed in and can't sign out.

**Comment by vitekr** [comment]
Same issue here. Running Station 2.0.9 on macOS 11.5.1

Station version 2.0.9
Electron 7.3.3
Chrome 78.0.3904.130
Node 12.8.1
v87.8.279.23-electron.0

**Comment by dadigu** [comment]
I'm running into the exact same issue as well. If I reinstall the app the issue still persists. I normally use AppCleaner to uninstall apps, it finds cache files and stuff related to the app. But AppCleaner does not pickup the data from Application Support, probably because if its naming `~/Library/Application Support/Stationv2` that appended "v2". So if I wipe out that folder then I can use teams again, but of course Station looses all configuration. Then If I reboot my machine or what ever then I get  back to the white screen, or the "We're sorry -- We've run into an issue" screen.

**Comment by viktor44** [comment]
#80
