### ISSUE TITLE
Spotify is an installable app but cannot be used

### ISSUE THREAD

**Issue by shaokatzu** [getstation/desktop-app#355]
When one logs in to Spotify via Station the error given is "Playback of protected content is not enabled." and lists the need for the "Widevine" plugin.

I suppose I don't know what else to say here, the issue seems straightforward but I don't see how it can be resolved client-side. Sorry if this isn't formatted properly or something, it's my first time posting on github.

Edit: I will add that this would be solvable perhaps if one could see the Google Widevine installation prompt, and be able to allow it. In my recent search for a new browser (before finding Station,) I installed Brave, and in going to the Spotify web app in that browser, it does indeed give an allow/deny prompt for the installation of Widevine.

**Comment by shaokatzu** [comment]
I will add that this would be solvable perhaps if one could see the Google Widevine installation prompt, and be able to allow it. In my recent search for a new browser I've installed Brave, and in going to the Spotify web app in that browser, it does indeed give an allow/deny prompt for the installation of Widevine.

**Comment by viktor44** [comment]
Spotify requires [Widevine DRM](https://www.widevine.com/solutions/widevine-drm) libraries to be installed.
The main problem is that Widevine software is not free and requires license agreement with Google.

Here are 2 solutions how it could be used (both haven't worked from the first try)
https://github.com/castlabs/electron-releases
https://www.electronjs.org/docs/latest/tutorial/testing-widevine-cdm

[Discussion](https://github.com/ferdium/ferdium-app/pull/720) about it.

I'm closing the issue because I don't think we will be able to fix it soon.
